version: '3'
services:
  post-db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  spring-app:
    # image: tg-channel-search-image
    build:
        context: ./spring/
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:postgresql://post-db:5432/tgapibot
    #   - SPRING_DATASOURCE_USERNAME=devq
    #   - SPRING_DATASOURCE_PASSWORD=devdev
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}

  flask-app:
    # image: telegram-export-image
    build:
        context: ./flask/
        dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"